import time 
print("|          |",end="\r",flush=True)
time.sleep(1)
print("|=>        |",end="\r",flush=True)
time.sleep(1)
print("|==>       |",end="\r",flush=True)
time.sleep(1)
print("|===>      |",end="\r",flush=True)
time.sleep(1)
print("|====>     |",end="\r",flush=True)
time.sleep(1)
print("|=====>    |",end="\r",flush=True)
time.sleep(1)
print("|======>   |",end="\r",flush=True)
time.sleep(1)
print("|=======>  |",end="\r",flush=True)
time.sleep(1)
print("|========> |",end="\r",flush=True)
time.sleep(1)
print("|==========|",end="\r",flush=True)
print("\nDone!")